# Generated by Django 5.2.15 on 2026-06-21 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Friendly name, e.g. 'Flutter - Tehran'", max_length=128)),
                ('url', models.URLField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to='accounts.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=512)),
                ('company', models.CharField(blank=True, max_length=256)),
                ('location', models.CharField(blank=True, max_length=256)),
                ('contract_type', models.CharField(blank=True, max_length=128)),
                ('posted_text', models.CharField(blank=True, max_length=64)),
                ('job_url', models.URLField(max_length=1000)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='jobs.searchquery')),
            ],
            options={
                'ordering': ['-found_at'],
                'constraints': [models.UniqueConstraint(fields=('search_query', 'external_id'), name='uniq_job_per_search')],
            },
        ),
    ]
