--
-- PostgreSQL database dump
--

\restrict tnmDS3axgSEXQGoJKrofj7GWQm8tPQg4CBYT1jqhUEi543fjSOIpv6KGTemV8dw

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_telegramuser; Type: TABLE; Schema: public; Owner: jobbot
--

CREATE TABLE public.accounts_telegramuser (
    id bigint NOT NULL,
    chat_id bigint NOT NULL,
    username character varying(64),
    first_name character varying(128),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_name character varying(128)
);


ALTER TABLE public.accounts_telegramuser OWNER TO jobbot;

--
-- Name: accounts_telegramuser_id_seq; Type: SEQUENCE; Schema: public; Owner: jobbot
--

ALTER TABLE public.accounts_telegramuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_telegramuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: jobbot
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO jobbot;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: jobbot
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: jobbot
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO jobbot;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: jobbot
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: jobbot
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO jobbot;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: jobbot
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: jobbot
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO jobbot;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: jobbot
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO jobbot;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: jobbot
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: jobbot
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: jobbot
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO jobbot;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: jobbot
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: jobbot
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO jobbot;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: jobbot
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: jobbot
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO jobbot;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: jobbot
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: jobbot
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO jobbot;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: jobbot
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: jobbot
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO jobbot;

--
-- Name: jobs_jobposting; Type: TABLE; Schema: public; Owner: jobbot
--

CREATE TABLE public.jobs_jobposting (
    id bigint NOT NULL,
    external_id character varying(64) NOT NULL,
    title character varying(512) NOT NULL,
    company character varying(256) NOT NULL,
    location character varying(256) NOT NULL,
    contract_type character varying(128) NOT NULL,
    posted_text character varying(64) NOT NULL,
    job_url character varying(1000) NOT NULL,
    found_at timestamp with time zone NOT NULL,
    notified boolean NOT NULL,
    search_query_id bigint NOT NULL
);


ALTER TABLE public.jobs_jobposting OWNER TO jobbot;

--
-- Name: jobs_jobposting_id_seq; Type: SEQUENCE; Schema: public; Owner: jobbot
--

ALTER TABLE public.jobs_jobposting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_jobposting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jobs_searchquery; Type: TABLE; Schema: public; Owner: jobbot
--

CREATE TABLE public.jobs_searchquery (
    id bigint NOT NULL,
    title character varying(128) NOT NULL,
    url character varying(1000) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.jobs_searchquery OWNER TO jobbot;

--
-- Name: jobs_searchquery_id_seq; Type: SEQUENCE; Schema: public; Owner: jobbot
--

ALTER TABLE public.jobs_searchquery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_searchquery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_telegramuser; Type: TABLE DATA; Schema: public; Owner: jobbot
--

COPY public.accounts_telegramuser (id, chat_id, username, first_name, is_active, created_at, last_name) FROM stdin;
3	796965271	mrmahdi_00	ʍǟɦɖɨ	t	2026-06-26 16:39:53.398587+00	\N
4	570420782	amirhosseinbanaei	amir hossein	t	2026-06-27 21:15:44.151755+00	
5	-1003714725188	MrTakDev	erfan	t	2026-07-02 11:48:40.021353+00	\N
6	7925430720	Amirmahdihoseinzadeh	میتی	t	2026-07-04 09:17:53.300017+00	\N
1	1075119392	MrTakDev	erfan	t	2026-06-24 16:40:59.443141+00	
2	8497951035	\N	MrTak	t	2026-06-24 18:53:01.491418+00	\N
7	262287176	spehrsd	Sepehr	t	2026-07-12 11:18:55.940799+00	
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: jobbot
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: jobbot
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: jobbot
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add telegram user	7	add_telegramuser
26	Can change telegram user	7	change_telegramuser
27	Can delete telegram user	7	delete_telegramuser
28	Can view telegram user	7	view_telegramuser
29	Can add search query	8	add_searchquery
30	Can change search query	8	change_searchquery
31	Can delete search query	8	delete_searchquery
32	Can view search query	8	view_searchquery
33	Can add job posting	9	add_jobposting
34	Can change job posting	9	change_jobposting
35	Can delete job posting	9	delete_jobposting
36	Can view job posting	9	view_jobposting
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: jobbot
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: jobbot
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: jobbot
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: jobbot
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: jobbot
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	accounts	telegramuser
8	jobs	searchquery
9	jobs	jobposting
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: jobbot
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	accounts	0001_initial	2026-06-24 16:39:17.243611+00
2	contenttypes	0001_initial	2026-06-24 16:39:17.262001+00
3	auth	0001_initial	2026-06-24 16:39:17.458211+00
4	admin	0001_initial	2026-06-24 16:39:17.524493+00
5	admin	0002_logentry_remove_auto_add	2026-06-24 16:39:17.545295+00
6	admin	0003_logentry_add_action_flag_choices	2026-06-24 16:39:17.567198+00
7	contenttypes	0002_remove_content_type_name	2026-06-24 16:39:17.59303+00
8	auth	0002_alter_permission_name_max_length	2026-06-24 16:39:17.602904+00
9	auth	0003_alter_user_email_max_length	2026-06-24 16:39:17.612326+00
10	auth	0004_alter_user_username_opts	2026-06-24 16:39:17.622626+00
11	auth	0005_alter_user_last_login_null	2026-06-24 16:39:17.632179+00
12	auth	0006_require_contenttypes_0002	2026-06-24 16:39:17.634291+00
13	auth	0007_alter_validators_add_error_messages	2026-06-24 16:39:17.644807+00
14	auth	0008_alter_user_username_max_length	2026-06-24 16:39:17.66071+00
15	auth	0009_alter_user_last_name_max_length	2026-06-24 16:39:17.67265+00
16	auth	0010_alter_group_name_max_length	2026-06-24 16:39:17.687572+00
17	auth	0011_update_proxy_permissions	2026-06-24 16:39:17.697671+00
18	auth	0012_alter_user_first_name_max_length	2026-06-24 16:39:17.711331+00
19	jobs	0001_initial	2026-06-24 16:39:17.7535+00
20	sessions	0001_initial	2026-06-24 16:39:17.772646+00
34	accounts	0002_telegramuser_last_name	2026-06-24 18:50:08.587835+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: jobbot
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: jobs_jobposting; Type: TABLE DATA; Schema: public; Owner: jobbot
--

COPY public.jobs_jobposting (id, external_id, title, company, location, contract_type, posted_text, job_url, found_at, notified, search_query_id) FROM stdin;
402	tGta	توسعه دهنده فول استک (هوش مصنوعی)	برتینا | Bertina	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/bertina/jobs/tGta/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D8%AF%D9%87%D9%86%D8%AF%D9%87-%D9%81%D9%88%D9%84-%D8%A7%D8%B3%D8%AA%DA%A9-%D9%87%D9%88%D8%B4-%D9%85%D8%B5%D9%86%D9%88%D8%B9%DB%8C-%D8%AF%D8%B1-%D8%A8%D8%B1%D8%AA%DB%8C%D9%86%D8%A7	2026-07-02 13:28:51.804175+00	t	22
404	1418592	Front-End Developer (Next.js) - آقا	صرافی ایکس پی	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1418592	2026-07-03 07:58:51.717231+00	t	21
418	1423530	Senior Front-End Developer (React) - آقا	ماها	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1423530	2026-07-06 12:58:51.663192+00	t	21
433	1441968	Senior Front-End Developer	سلزکوچینگ	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1441968	2026-07-08 13:28:51.747269+00	t	21
449	1445388	Front-End Developer (Vue.js)	توسعه فناوری نرم افزار یسنا	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1445388	2026-07-11 13:58:51.933934+00	t	21
473	tGkB	Senior Product Manager	حامی پیشگامان | Hamipishgaman	تهران، تهران	قرارداد تمام‌وقت	۱ روز پیش	https://jobinja.ir/companies/hami-4/jobs/tGkB/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-product-manager-%D8%AF%D8%B1-%D8%AD%D8%A7%D9%85%DB%8C-%D9%BE%DB%8C%D8%B4%DA%AF%D8%A7%D9%85%D8%A7%D9%86	2026-07-12 11:28:54.898718+00	t	27
263	taFz	React.js) Front-End Developer)	کارنو | Karno	تهران، تهران	قرارداد تمام‌وقت	۵ روز پیش	https://jobinja.ir/companies/karno-11/jobs/taFz/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-react-js-front-end-developer-%D8%AF%D8%B1-%DA%A9%D8%A7%D8%B1%D9%86%D9%88	2026-06-27 21:28:53.973968+00	t	22
257	ta7M	برنامه‌نویس فرانت‌اند (ReactJS)	آدانیک افزار | Adanic	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/adanic/jobs/ta7M/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-%D9%81%D8%B1%D8%A7%D9%86%D8%AA-%D8%A7%D9%86%D8%AF-reactjs-%D8%AF%D8%B1-%D8%A2%D8%AF%D8%A7%D9%86%DB%8C%DA%A9-%D8%A7%D9%81%D8%B2%D8%A7%D8%B1	2026-06-27 21:28:53.946927+00	t	22
475	ta5A	Product Designer	فراز | Faraz	تهران، تهران	قرارداد تمام‌وقت	۲ روز پیش	https://jobinja.ir/companies/faraz-17/jobs/ta5A/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-product-designer-%D8%AF%D8%B1-%D9%81%D8%B1%D8%A7%D8%B2	2026-07-12 11:28:54.907636+00	t	27
278	1432824	برنامه نویس Front-End	هلدینگ آوای جهانبین پارسیان	تهران، تهران	تمام وقت	دیروز	https://jobvision.ir/jobs/1432824	2026-06-27 21:43:52.673059+00	t	21
277	1432019	Front-End Developer	کارمود	تهران، تهران	تمام وقت	دیروز	https://jobvision.ir/jobs/1432019	2026-06-27 21:43:52.665629+00	t	21
308	1434701	Senior Frontend Developer (Next.js)	کاریزما	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1434701	2026-06-29 07:58:52.574615+00	t	21
339	1437945	Senior React Developer	گلپخش اول	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1437945	2026-07-01 12:43:53.086396+00	t	21
403	1295186	Senior Full-Stack Software Engineer (PHP with Vue.js/Angular/React.js)	بیراد	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1295186	2026-07-02 13:58:51.59604+00	t	21
405	tG2g	برنامه‌نویس Front-End	راشین طب سلامت | Rashein	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/rashein/jobs/tG2g/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-front-end-%D8%AF%D8%B1-%D8%B1%D8%A7%D8%B4%DB%8C%D9%86-%D8%B7%D8%A8-%D8%B3%D9%84%D8%A7%D9%85%D8%AA	2026-07-03 07:58:51.979629+00	t	22
419	1440742	توسعه‌دهنده ارشد فرانت‌اند (React)	گارنو پرگاس	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1440742	2026-07-07 05:28:51.81523+00	t	21
434	1442874	برنامه نویس Angular	نو اندیشان صنعت داده ویرا	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1442874	2026-07-08 13:58:51.900693+00	t	21
450	tG7X	(Senior Front-End Developer (React	ازکی سرمایه | azki sarmayeh	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/daran/jobs/tG7X/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-front-end-developer-react-%D8%AF%D8%B1-%D8%A7%D8%B2%DA%A9%DB%8C-%D8%B3%D8%B1%D9%85%D8%A7%DB%8C%D9%87	2026-07-11 13:58:52.306084+00	t	22
476	1446318	Senior Frontend Developer	اکوتراست	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1446318	2026-07-12 11:58:52.007139+00	t	21
406	1409969	Senior Front-End Developer	نئوبانک اقتصاد نوین	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1409969	2026-07-03 13:28:51.538813+00	t	21
420	1440477	Technical Lead (Full-Stack)	سعادت رنت	تهران، تهران	تمام وقت یا پاره وقت	امروز	https://jobvision.ir/jobs/1440477	2026-07-07 08:28:51.885891+00	t	21
435	tGUr	Senior Front-End Engineer	نورو ویژن | Noro Vision	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/norovision/jobs/tGUr/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-front-end-engineer-%D8%AF%D8%B1-%D9%86%D9%88%D8%B1%D9%88-%D9%88%DB%8C%DA%98%D9%86	2026-07-09 06:58:52.562813+00	t	22
436	tGUA	Junior Front-End Developer	کارگزاری توازن بازار | Tavazon Bazar Brokerage	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/tavazon-bazar-brokerage/jobs/tGUA/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-junior-front-end-developer-%D8%AF%D8%B1-%DA%A9%D8%A7%D8%B1%DA%AF%D8%B2%D8%A7%D8%B1%DB%8C-%D8%AA%D9%88%D8%A7%D8%B2%D9%86-%D8%A8%D8%A7%D8%B2%D8%A7%D8%B1	2026-07-09 06:58:52.567194+00	t	22
451	1445054	برنامه نویس وب	تعاونی خدمات آموزشی کارکنان سازمان سنجش	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1445054	2026-07-11 14:13:52.057311+00	t	21
477	1446805	Full-Stack Developer	مهسان	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1446805	2026-07-12 12:13:51.98624+00	t	21
304	1433876	توسعه‌دهنده فرانت‌اند	ستیغ فراافق	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1433876	2026-06-28 12:28:54.503427+00	t	21
305	1434037	Senior Front-End Developer	گروه میلی	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1434037	2026-06-28 12:28:54.509109+00	t	21
310	1433785	Front-End Developer	همنشین	تهران، تهران	تمام وقت | دورکاری	امروز	https://jobvision.ir/jobs/1433785	2026-06-29 10:13:52.810979+00	t	21
315	1435652	برنامه‌نویس بک‌اند	مرکز هوش صنعتی پارت	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1435652	2026-06-29 14:13:54.560469+00	t	21
318	1426587	Senior Front-End Developer (React)	داده آمای داتیس	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1426587	2026-06-30 12:58:55.168224+00	t	21
319	1417165	برنامه نویس Full-Stack	مدام	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1417165	2026-06-30 12:58:55.176739+00	t	21
320	1399844	توسعه‌دهنده Full-Stack (.NET / React)	رهیافت داده پردازی آرکا	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1399844	2026-06-30 12:58:55.180277+00	t	21
321	1423084	Back-End Developer و Maintenance Support	بانک رفاه کارگران	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1423084	2026-06-30 12:58:55.183544+00	t	21
322	1416511	کارشناس پشتیبانی (شیفت عصر)	آسان طراحان هوشمند	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1416511	2026-06-30 12:58:55.186246+00	t	21
323	1415402	full stack developer	صنایع غذایی مرد کوهستان	تهران، تهران	تمام وقت	دیروز	https://jobvision.ir/jobs/1415402	2026-06-30 12:58:55.192219+00	t	21
324	1415420	Back-End Developer	صنایع غذایی مرد کوهستان	تهران، تهران	تمام وقت	دیروز	https://jobvision.ir/jobs/1415420	2026-06-30 12:58:55.195571+00	t	21
340	1434514	React Developer	کادیت	تهران، تهران	تمام وقت یا پاره وقت	امروز	https://jobvision.ir/jobs/1434514	2026-07-01 14:28:52.984005+00	t	21
407	1438846	Senior Java Developer (Technical Owner)	سریع ترابر ماهان	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1438846	2026-07-04 05:28:51.817221+00	t	21
258	taa0	توسعه دهنده فول استک (هوش مصنوعی)	برتینا | Bertina	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/bertina/jobs/taa0/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D8%AF%D9%87%D9%86%D8%AF%D9%87-%D9%81%D9%88%D9%84-%D8%A7%D8%B3%D8%AA%DA%A9-%D9%87%D9%88%D8%B4-%D9%85%D8%B5%D9%86%D9%88%D8%B9%DB%8C-%D8%AF%D8%B1-%D8%A8%D8%B1%D8%AA%DB%8C%D9%86%D8%A7	2026-06-27 21:28:53.954464+00	t	22
259	ABuu	برنامه‌نویس ارشد (Front-End (React	داده پردازی خوارزمی | DP Kharazmi	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/dpkharazmi/jobs/ABuu/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-%D8%A7%D8%B1%D8%B4%D8%AF-front-end-react-%D8%AF%D8%B1-%D8%AF%D8%A7%D8%AF%D9%87-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2%DB%8C-%D8%AE%D9%88%D8%A7%D8%B1%D8%B2%D9%85%DB%8C	2026-06-27 21:28:53.958789+00	t	22
260	taO7	ReactJs-Remote) Senior Front-End Developer)	ترون هاب | Tronhub	تهران، تهران	قرارداد دورکاری	۳ روز پیش	https://jobinja.ir/companies/tronhub/jobs/taO7/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-reactjs-remote-senior-front-end-developer-%D8%AF%D8%B1-%D8%AA%D8%B1%D9%88%D9%86-%D9%87%D8%A7%D8%A8	2026-06-27 21:28:53.962999+00	t	22
261	tHCE	Full-Stack Web Developer (‌Backend PHP Laravel)	واقعیت مطلوب پارس | Alpha Reality	تهران، تهران	قرارداد تمام‌وقت	۴ روز پیش	https://jobinja.ir/companies/alpha-reality-1/jobs/tHCE/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-full-stack-web-developer-backend-php-laravel-%D8%AF%D8%B1-%D9%88%D8%A7%D9%82%D8%B9%DB%8C%D8%AA-%D9%85%D8%B7%D9%84%D9%88%D8%A8-%D9%BE%D8%A7%D8%B1%D8%B3	2026-06-27 21:28:53.967297+00	t	22
262	taF1	React) Front-End Developer-آقا)	توسعه فناوری اطلاعات استیناس | Stinas	تهران، تهران	قرارداد تمام‌وقت	۴ روز پیش	https://jobinja.ir/companies/tofan/jobs/taF1/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-react-front-end-developer-%D8%A2%D9%82%D8%A7-%D8%AF%D8%B1-%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D9%81%D9%86%D8%A7%D9%88%D8%B1%DB%8C-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA-%D8%A7%D8%B3%D8%AA%DB%8C%D9%86%D8%A7%D8%B3	2026-06-27 21:28:53.970987+00	t	22
264	taz5	Front-End Developer	تپسل | Tapsell	تهران، تهران	قرارداد تمام‌وقت	۶ روز پیش	https://jobinja.ir/companies/tapsell/jobs/taz5/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-front-end-developer-%D8%AF%D8%B1-%D8%AA%D9%BE%D8%B3%D9%84	2026-06-27 21:28:53.977646+00	t	22
265	tppD	ReactJs) Senior Front-End Developer)	فناوری‌های علوم داده حسابا | Hesaba	تهران، تهران	قرارداد تمام‌وقت	۶ روز پیش	https://jobinja.ir/companies/hesaba/jobs/tppD/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-reactjs-senior-front-end-developer-%D8%AF%D8%B1-%D9%81%D9%86%D8%A7%D9%88%D8%B1%DB%8C-%D9%87%D8%A7%DB%8C-%D8%B9%D9%84%D9%88%D9%85-%D8%AF%D8%A7%D8%AF%D9%87-%D8%AD%D8%B3%D8%A7%D8%A8%D8%A7	2026-06-27 21:28:53.980664+00	t	22
266	tpPy	Senior Front-End Developer	همکاران سیستم | System Group	تهران، تهران	قرارداد تمام‌وقت	۶ روز پیش	https://jobinja.ir/companies/system-group/jobs/tpPy/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-front-end-developer-%D8%AF%D8%B1-%D9%87%D9%85%DA%A9%D8%A7%D8%B1%D8%A7%D9%86-%D8%B3%DB%8C%D8%B3%D8%AA%D9%85	2026-06-27 21:28:53.983006+00	t	22
421	1424395	Senior Angular Developer	فرینه فناور	تهران، تهران	تمام وقت	10 روز پیش	https://jobvision.ir/jobs/1424395	2026-07-07 08:58:51.813995+00	t	21
437	1443007	CTO (Hands-on | Full-stack | AI, BI, BPMS)	گروه توسعه اقتصادی نگار	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1443007	2026-07-09 12:28:51.864057+00	t	21
452	1446018	کارشناس ارشد Full Stack Developer - آقا	شرکت آراسب پیشتاز	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1446018	2026-07-12 08:28:52.071701+00	t	21
408	52354852	برنامه نویس ASP.NET، هوش مصنوعی و اپلیکیشن موبایل	تحلیل گران آمارد نوین آمل	آمل	تمام وقت	جدید	https://www.e-estekhdam.com/kh2c3q-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-asp-net-%D9%87%D9%88%D8%B4-%D9%85%D8%B5%D9%86%D9%88%D8%B9%DB%8C-%D9%88-%D8%A7%D9%BE%D9%84	2026-07-04 08:28:52.620477+00	t	23
422	52356292	برنامه‌نویس Flutter	ایمن موج توس	شهرک صنعتی توس	تمام وقت	جدید	https://www.e-estekhdam.com/k6e2of-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%88%DB%8C%D8%B3-flutter-%D8%AF%D8%B1-%D8%A7%DB%8C%D9%85%D9%86-%D9%85%D9%88%D8%AC-%D8%AA%D9%88%D8%B3	2026-07-07 10:28:52.708459+00	t	23
438	1443668	برنامه‌نویس ارشد Front-End (React + Vite)	رسام هنر رایکا	تهران، تهران	تمام وقت یا پاره وقت | دورکاری	امروز	https://jobvision.ir/jobs/1443668	2026-07-09 16:28:51.930636+00	t	21
453	1445266	برنامه‌نویس اندروید (Android Developer)	مرکز نوآوری و شتابدهی برنا	تهران، تهران	تمام وقت یا پاره وقت | دورکاری	امروز	https://jobvision.ir/jobs/1445266	2026-07-12 08:43:52.087083+00	t	21
267	tazH	برنامه‌نویس React	فناوران اطلاعات خبره | Fanavaran	تهران، تهران	قرارداد تمام‌وقت	۶ روز پیش	https://jobinja.ir/companies/fanavaran-5/jobs/tazH/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-react-%D8%AF%D8%B1-%D9%81%D9%86%D8%A7%D9%88%D8%B1%D8%A7%D9%86-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA-%D8%AE%D8%A8%D8%B1%D9%87	2026-06-27 21:28:53.986289+00	t	22
268	ta6r	Front-End Developer (دورکاری)	بمان | Beman	تهران، تهران	قرارداد دورکاری	۷ روز پیش	https://jobinja.ir/companies/beman/jobs/ta6r/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-front-end-developer-%D8%AF%D9%88%D8%B1%DA%A9%D8%A7%D8%B1%DB%8C-%D8%AF%D8%B1-%D8%A8%D9%85%D8%A7%D9%86	2026-06-27 21:28:53.988693+00	t	22
269	ta0G	برنامه‌نویس Front-End	مهندسی صنایع یاس ارغوانی | Sanaye Yaas Arghavani	تهران، تهران	قرارداد تمام‌وقت	۷ روز پیش	https://jobinja.ir/companies/sanaye-yaas-arghavani-1/jobs/ta0G/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-front-end-%D8%AF%D8%B1-%D9%85%D9%87%D9%86%D8%AF%D8%B3%DB%8C-%D8%B5%D9%86%D8%A7%DB%8C%D8%B9-%DB%8C%D8%A7%D8%B3-%D8%A7%D8%B1%D8%BA%D9%88%D8%A7%D9%86%DB%8C	2026-06-27 21:28:53.992014+00	t	22
270	tpj3	برنامه‌نویس فرانت اند (React/Next)	توسعه فناوری رفاه پردیس | RPTD	تهران، تهران	قرارداد تمام‌وقت	۷ روز پیش	https://jobinja.ir/companies/rptd/jobs/tpj3/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-%D9%81%D8%B1%D8%A7%D9%86%D8%AA-%D8%A7%D9%86%D8%AF-react-next-%D8%AF%D8%B1-%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D9%81%D9%86%D8%A7%D9%88%D8%B1%DB%8C-%D8%B1%D9%81%D8%A7%D9%87-%D9%BE%D8%B1%D8%AF%DB%8C%D8%B3	2026-06-27 21:28:53.995504+00	t	22
271	taYX	Mobile App Developer	آلومینیوم دیتاست | Aluminium Dataset	تهران، تهران	قرارداد تمام‌وقت	۱۰ روز پیش	https://jobinja.ir/companies/aluminium-dataset/jobs/taYX/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-mobile-app-developer-%D8%AF%D8%B1-%D8%A2%D9%84%D9%88%D9%85%DB%8C%D9%86%DB%8C%D9%88%D9%85-%D8%AF%DB%8C%D8%AA%D8%A7%D8%B3%D8%AA	2026-06-27 21:28:53.998534+00	t	22
272	tkz9	توسعه دهنده ارشد فرانت (Senior Front Developer-React)	گلدیکا | Goldika	تهران، تهران	قرارداد تمام‌وقت	۱۰ روز پیش	https://jobinja.ir/companies/goldika/jobs/tkz9/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D8%AF%D9%87%D9%86%D8%AF%D9%87-%D8%A7%D8%B1%D8%B4%D8%AF-%D9%81%D8%B1%D8%A7%D9%86%D8%AA-senior-front-developer-react-%D8%AF%D8%B1-%DA%AF%D9%84%D8%AF%DB%8C%DA%A9%D8%A7	2026-06-27 21:28:54.001534+00	t	22
273	tp8w	Frontend Developer (React)	امن افزار گستر شریف | Amn Afzar Gostare Sharif	تهران، تهران	قرارداد تمام‌وقت	۱۱ روز پیش	https://jobinja.ir/companies/amnafzar/jobs/tp8w/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-frontend-developer-react-%D8%AF%D8%B1-%D8%A7%D9%85%D9%86-%D8%A7%D9%81%D8%B2%D8%A7%D8%B1-%DA%AF%D8%B3%D8%AA%D8%B1-%D8%B4%D8%B1%DB%8C%D9%81	2026-06-27 21:28:54.004762+00	t	22
274	tpKk	Frontend Engineering Intern (React/TypeScript)	آینده پژوهان لوتوس | Lotus Futurists	تهران، تهران	قرارداد تمام‌وقت	۱۱ روز پیش	https://jobinja.ir/companies/aplotus-1/jobs/tpKk/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-frontend-engineering-intern-react-typescript-%D8%AF%D8%B1-%D8%A2%DB%8C%D9%86%D8%AF%D9%87-%D9%BE%DA%98%D9%88%D9%87%D8%A7%D9%86-%D9%84%D9%88%D8%AA%D9%88%D8%B3	2026-06-27 21:28:54.008426+00	t	22
275	tpKw	Frontend Engineer (React/TypeScript)	آینده پژوهان لوتوس | Lotus Futurists	تهران، تهران	قرارداد تمام‌وقت	۱۱ روز پیش	https://jobinja.ir/companies/aplotus-1/jobs/tpKw/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-frontend-engineer-react-typescript-%D8%AF%D8%B1-%D8%A2%DB%8C%D9%86%D8%AF%D9%87-%D9%BE%DA%98%D9%88%D9%87%D8%A7%D9%86-%D9%84%D9%88%D8%AA%D9%88%D8%B3	2026-06-27 21:28:54.010902+00	t	22
276	tphY	Senior Front-End Developer	توسعه فناوری گروه فارابی | Farabi Group Tech Development Co.	تهران، تهران	قرارداد تمام‌وقت	۱۱ روز پیش	https://jobinja.ir/companies/soshyant-1/jobs/tphY/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-front-end-developer-%D8%AF%D8%B1-%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D9%81%D9%86%D8%A7%D9%88%D8%B1%DB%8C-%DA%AF%D8%B1%D9%88%D9%87-%D9%81%D8%A7%D8%B1%D8%A7%D8%A8%DB%8C	2026-06-27 21:28:54.013925+00	t	22
409	1439347	Front-End Developer (React.js)	شرکت مشاوره مدیریت بهین راستین پارس	تهران، تهران	تمام وقت | دورکاری	امروز	https://jobvision.ir/jobs/1439347	2026-07-04 10:58:51.893069+00	t	21
423	1441272	Senior Frontend Developer (React / Next.js)	گروه حمل و نقل بین المللی ادمیرال	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1441272	2026-07-07 12:58:51.70524+00	t	21
424	1441275	Senior QA Engineer (Quality Engineer)	گروه حمل و نقل بین المللی ادمیرال	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1441275	2026-07-07 12:58:51.717589+00	t	21
439	taK8	(Senior Front-End Developer (React	مدیانا | Mediana	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/mediana/jobs/taK8/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-front-end-developer-react-%D8%AF%D8%B1-%D9%85%D8%AF%DB%8C%D8%A7%D9%86%D8%A7	2026-07-11 05:43:52.2599+00	t	22
454	1446510	Software Engineer (Frontend-focused)	یکتانت	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1446510	2026-07-12 11:28:52.02129+00	t	21
279	1432234	طراح و توسعه‌دهنده وب (AI)	سازمانی فعال در حوزه تجارت / بازرگانی	تهران، تهران	تمام وقت یا پاره وقت | دورکاری	دیروز	https://jobvision.ir/jobs/1432234	2026-06-27 21:43:52.677351+00	t	21
280	1345455	Senior Software Engineer (Go)	اسنپ ساپلای	تهران، تهران	تمام وقت	دیروز	https://jobvision.ir/jobs/1345455	2026-06-27 21:43:52.680839+00	t	21
281	1433046	کارشناس سامانه و برنامه‌نویس	آزمایشگاه کالیبراسیون دانش بنیان بهینه فرآیند آزما	تهران، اسلام شهر	تمام وقت	دیروز	https://jobvision.ir/jobs/1433046	2026-06-27 21:43:52.684283+00	t	21
282	1430607	توسعه دهنده نرم افزار Full Stack Developer	شاتل موبایل	تهران، تهران	تمام وقت	5 روز پیش	https://jobvision.ir/jobs/1430607	2026-06-27 21:43:52.688731+00	t	21
283	1430716	توسعه‌دهنده Full Stack (Laravel / Vue.js / Inertia.js)	گروه پایدار	تهران، تهران	تمام وقت	5 روز پیش	https://jobvision.ir/jobs/1430716	2026-06-27 21:43:52.692138+00	t	21
284	1429604	(Tech Lead (Java	گروه میلی	تهران، تهران	تمام وقت	5 روز پیش	https://jobvision.ir/jobs/1429604	2026-06-27 21:43:52.695202+00	t	21
285	1429113	توسعه‌دهنده فرانت‌اند	گروه فن آوری اطلاعات و ارتباطات رایان بارای	تهران، تهران	تمام وقت	6 روز پیش	https://jobvision.ir/jobs/1429113	2026-06-27 21:43:52.698125+00	t	21
286	1429678	کارشناس ارشد فرانت‌اند (React)	توسعه نرم افزارهای بانکی نگاه فردای کارآفرین	تهران، تهران	تمام وقت	6 روز پیش	https://jobvision.ir/jobs/1429678	2026-06-27 21:43:52.701157+00	t	21
287	1429720	Senior Front-End Developer (React)	تسکا صنعت	تهران، تهران	تمام وقت	6 روز پیش	https://jobvision.ir/jobs/1429720	2026-06-27 21:43:52.703989+00	t	21
288	1429473	توسعه دهنده Front-End	گروه مشاوران آری	تهران، تهران	تمام وقت	6 روز پیش	https://jobvision.ir/jobs/1429473	2026-06-27 21:43:52.706897+00	t	21
289	1428660	Senior Frontend Engineer (React / Next.js)	سازمانی فعال در حوزه فناوری اطلاعات / نرم افزار و سخت افزار	تهران، تهران	تمام وقت	6 روز پیش	https://jobvision.ir/jobs/1428660	2026-06-27 21:43:52.709871+00	t	21
290	1429086	برنامه نویس فول استک (Full Stack Developer)	ایکس چیف	تهران، تهران	تمام وقت | دورکاری	6 روز پیش	https://jobvision.ir/jobs/1429086	2026-06-27 21:43:52.712557+00	t	21
291	1428803	مهندس ارشد نرم‌افزار Full-Stack (Django + JS Framework)	شرکت شیمیایی بهداش	تهران، تهران	تمام وقت	6 روز پیش	https://jobvision.ir/jobs/1428803	2026-06-27 21:43:52.715296+00	t	21
292	1287969	Frontend Developer (React)	شرکت خدمات انفورماتیک	تهران، تهران	تمام وقت	7 روز پیش	https://jobvision.ir/jobs/1287969	2026-06-27 21:43:52.718118+00	t	21
293	1427717	برنامه نویس Front-End	تپسل	تهران، تهران	تمام وقت	7 روز پیش	https://jobvision.ir/jobs/1427717	2026-06-27 21:43:52.720418+00	t	21
294	1427578	برنامه نویس React	فناوران اطلاعات خبره	تهران، تهران	تمام وقت | دورکاری	دیروز	https://jobvision.ir/jobs/1427578	2026-06-27 21:43:52.722888+00	t	21
295	1426320	Front End Developer (React.js)	گروه MCI NEXT	تهران، تهران	تمام وقت	7 روز پیش	https://jobvision.ir/jobs/1426320	2026-06-27 21:43:52.725526+00	t	21
296	1410281	کارشناس برنامه نویسی (React-Next.js)	آواکس	تهران، تهران	تمام وقت	7 روز پیش	https://jobvision.ir/jobs/1410281	2026-06-27 21:43:52.728151+00	t	21
297	1433193	برنامه‌نویس ارشد Python / Node.js	گروه سلامت آرامش	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1433193	2026-06-28 06:13:52.852993+00	t	21
298	1431518	کارشناس طراحی سایت و سئو (توسعه وب)	کافی فراور پارسه	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1431518	2026-06-28 06:28:52.783402+00	t	21
299	tpX5	(Senior Front-End Developer (React	مهندسی تحقیق و توسعه ارتباطات صمیم رایانه | .Samim Rayaneh Communication Research and Development Engineering Co	تهران، تهران	قرارداد تمام‌وقت	۱۱ روز پیش	https://jobinja.ir/companies/samim/jobs/tpX5/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-front-end-developer-react-%D8%AF%D8%B1-%D9%85%D9%87%D9%86%D8%AF%D8%B3%DB%8C-%D8%AA%D8%AD%D9%82%DB%8C%D9%82-%D9%88-%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D8%A7%D8%B1%D8%AA%D8%A8%D8%A7%D8%B7%D8%A7%D8%AA-%D8%B5%D9%85%DB%8C%D9%85-%D8%B1%D8%A7%DB%8C%D8%A7%D9%86%D9%87	2026-06-28 06:28:53.340853+00	t	22
300	trQi	(Senior Front-End Developer (React	پردازش اطلاعات مالی مبنا | Mabna DP	تهران، تهران	قرارداد تمام‌وقت	۱۲ روز پیش	https://jobinja.ir/companies/mabna-dp/jobs/trQi/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-front-end-developer-react-%D8%AF%D8%B1-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2%D8%B4-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA-%D9%85%D8%A7%D9%84%DB%8C-%D9%85%D8%A8%D9%86%D8%A7	2026-06-28 09:28:53.457991+00	t	22
301	1433514	برنامه‌نویس فرانت‌اند React	کالاپینگ	تهران، تهران	تمام وقت | دورکاری	امروز	https://jobvision.ir/jobs/1433514	2026-06-28 09:43:54.935637+00	t	21
302	taEh	برنامه‌نویس React	فناوران اطلاعات خبره | Fanavaran	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/fanavaran-5/jobs/taEh/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-react-%D8%AF%D8%B1-%D9%81%D9%86%D8%A7%D9%88%D8%B1%D8%A7%D9%86-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA-%D8%AE%D8%A8%D8%B1%D9%87	2026-06-28 09:58:55.400661+00	t	22
303	1426342	مهندس ارشد نرم‌افزار (Lead Engineer)	شرکت آریا اندیش سورنا	تهران، تهران	تمام وقت یا پاره وقت | دورکاری	امروز	https://jobvision.ir/jobs/1426342	2026-06-28 11:43:52.690789+00	t	21
306	1434180	برنامه نویس React Native	توسعه سامانه های نرم افزاری نگین - توسن	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1434180	2026-06-28 14:58:52.871917+00	t	21
330	1437292	Senior Front-end Developer	اُکالا	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1437292	2026-07-01 07:28:54.683554+00	t	21
410	1439646	Senior Full-Stack Developer (AI-Native)	خودرو45	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1439646	2026-07-04 12:13:51.679308+00	t	21
307	tadq	توسعه‌دهنده (Front-End (React	کارنو | Karno	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/karno-11/jobs/tadq/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D8%AF%D9%87%D9%86%D8%AF%D9%87-front-end-react-%D8%AF%D8%B1-%DA%A9%D8%A7%D8%B1%D9%86%D9%88	2026-06-29 07:13:53.524814+00	t	22
309	1434775	برنامه‌نویس فرانت‌اند (Front-end Developer)	شرکت ارتباطات مبین نت	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1434775	2026-06-29 08:43:54.377234+00	t	21
311	1435301	توسعه‌دهنده فول‌استک وب	صنایع نساجی تارا ریس آریا	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1435301	2026-06-29 11:28:54.525238+00	t	21
411	1416811	Front-End Developer	جم جویز	تهران، تهران	تمام وقت	24 روز پیش	https://jobvision.ir/jobs/1416811	2026-07-04 12:28:52.561984+00	t	24
314	1431310	Mid-Level Full Stack Python Engineer	گروه نوآور ثاقب	تهران، تهران	تمام وقت | دورکاری	امروز	https://jobvision.ir/jobs/1431310	2026-06-29 13:43:53.294547+00	t	21
317	1436469	کارشناس توسعه نرم‌افزار (Full Stack Developer)	گروه اقتصادی تاو	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1436469	2026-06-30 11:28:54.618668+00	t	21
325	taHL	مدیر تیم برنامه‌نویسی (Technical Team Lead)	راهکارهای خلاق فناوری اطلاعات | Creative IT Solutions	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/aielts/jobs/taHL/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D9%85%D8%AF%DB%8C%D8%B1-%D8%AA%DB%8C%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3%DB%8C-technical-team-lead-%D8%AF%D8%B1-%D8%B1%D8%A7%D9%87%DA%A9%D8%A7%D8%B1%D9%87%D8%A7%DB%8C-%D8%AE%D9%84%D8%A7%D9%82-%D9%81%D9%86%D8%A7%D9%88%D8%B1%DB%8C-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA	2026-06-30 13:13:56.328293+00	t	22
326	ta8z	برنامه‌نویس ارشد فرانت‌اند (Senior Front-End (React) Developer)	ریتون | Riton	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/riton-4/jobs/ta8z/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-%D8%A7%D8%B1%D8%B4%D8%AF-%D9%81%D8%B1%D8%A7%D9%86%D8%AA-%D8%A7%D9%86%D8%AF-senior-front-end-react-developer-%D8%AF%D8%B1-%D8%B1%DB%8C%D8%AA%D9%88%D9%86	2026-06-30 13:13:56.334463+00	t	22
327	tkwj	Frontend Engineer	خانه هوش ایران | Iran Ai House	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/iran-ai-house/jobs/tkwj/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-frontend-engineer-%D8%AF%D8%B1-%D8%AE%D8%A7%D9%86%D9%87-%D9%87%D9%88%D8%B4-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86	2026-07-01 05:43:53.885794+00	t	22
425	1441241	Frontend Tech Lead (React / Next.js)	گروه حمل و نقل بین المللی ادمیرال	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1441241	2026-07-07 13:28:51.881676+00	t	21
440	1444384	Front-End Developer	گسترش فناوری های نوین	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1444384	2026-07-11 07:58:51.849329+00	t	21
331	taBw	React.js-Next.js) Front-End Developer)	حسابگر پرداز غرب (اینترنت تک نت) | Taknet	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/taknet/jobs/taBw/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-react-js-next-js-front-end-developer-%D8%AF%D8%B1-%D8%AD%D8%B3%D8%A7%D8%A8%DA%AF%D8%B1-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2-%D8%BA%D8%B1%D8%A8-%D8%A7%DB%8C%D9%86%D8%AA%D8%B1%D9%86%D8%AA-%D8%AA%DA%A9-%D9%86%D8%AA	2026-07-01 07:44:12.327275+00	t	22
334	1435045	Mid-Level Front-End Developer	بلوپی	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1435045	2026-07-01 08:28:54.626304+00	t	21
341	1413486	Senior Front-End Developer (React) - آقا	سیب ترش	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1413486	2026-07-01 15:28:52.845478+00	t	21
346	1420081	برنامه نویس Full-Stack	پژوهشگاه نصر	تهران، تهران	تمام وقت یا پاره وقت	6 روز پیش	https://jobvision.ir/jobs/1420081	2026-07-02 11:58:54.003441+00	t	24
347	1419833	توسعه‌دهنده فلاتر	شرکت ایده بنیان میلا	اصفهان، اصفهان	تمام وقت	9 روز پیش	https://jobvision.ir/jobs/1419833	2026-07-02 11:58:54.005874+00	t	24
348	1419347	توسعه‌دهنده بک‌اند (آشنا با فلاتر)	شرکت ایده بنیان میلا	اصفهان، اصفهان	تمام وقت	9 روز پیش	https://jobvision.ir/jobs/1419347	2026-07-02 11:58:54.009562+00	t	24
349	1429075	برنامه‌نویس Flutter	تجارت خودرو خسروانی	تهران، تهران	تمام وقت	10 روز پیش	https://jobvision.ir/jobs/1429075	2026-07-02 11:58:54.012476+00	t	24
350	1429057	برنامه‌نویس Backend	تجارت خودرو خسروانی	تهران، تهران	تمام وقت	10 روز پیش	https://jobvision.ir/jobs/1429057	2026-07-02 11:58:54.015531+00	t	24
351	1425532	توسعه‌دهنده موبایل	شرکت فنی و مهندسی نوید	اصفهان، خمینی شهر	تمام وقت	14 روز پیش	https://jobvision.ir/jobs/1425532	2026-07-02 11:58:54.018482+00	t	24
352	1417696	کارآموز طراح سایت	پیشرو تجارت افق	تهران، تهران	پاره وقت | دورکاری | کارآموزی	16 روز پیش	https://jobvision.ir/jobs/1417696	2026-07-02 11:58:54.021199+00	t	24
353	1418412	بازاریاب و فروشنده (خدمات طراحی وب‌سایت و اپلیکیشن)	آژانس طراحی مسترکد	گیلان، رشت	تمام وقت یا پاره وقت | دورکاری	18 روز پیش	https://jobvision.ir/jobs/1418412	2026-07-02 11:58:54.024352+00	t	24
354	1417442	Senior Flutter Developer	صرافی ایکس پی	تهران، تهران	تمام وقت	22 روز پیش	https://jobvision.ir/jobs/1417442	2026-07-02 11:58:54.026878+00	t	24
455	tGMY	Software Engineer (Frontend Focused)	یکتانت | Yektanet	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/yektanet/jobs/tGMY/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-software-engineer-frontend-focused-%D8%AF%D8%B1-%DB%8C%DA%A9%D8%AA%D8%A7%D9%86%D8%AA	2026-07-12 11:28:52.205362+00	t	22
332	ta5w	کارآموز برنامه‌نویسی React) Front-End-دورکاری)	رستاوا | Rastava	تهران، تهران	قرارداد کارآموزی	امروز	https://jobinja.ir/companies/d-c-develop-conquer/jobs/ta5w/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%DA%A9%D8%A7%D8%B1%D8%A2%D9%85%D9%88%D8%B2-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3%DB%8C-react-front-end-%D8%AF%D9%88%D8%B1%DA%A9%D8%A7%D8%B1%DB%8C-%D8%AF%D8%B1-%D8%B1%D8%B3%D8%AA%D8%A7%D9%88%D8%A7	2026-07-01 07:44:12.331769+00	t	22
333	1430665	سرپرست توسعه دهنده نرم‌افزار	شاتل موبایل	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1430665	2026-07-01 07:59:12.625092+00	t	21
335	1437458	برنامه نویس - آقا	فیدار پرداز تیوان (رایتک)	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1437458	2026-07-01 08:58:54.765549+00	t	21
336	ta3s	برنامه‌نویس Front-End (React & Next.js)	زیپرین | Ziprin	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/ziprin/jobs/ta3s/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-front-end-react-next-js-%D8%AF%D8%B1-%D8%B2%DB%8C%D9%BE%D8%B1%DB%8C%D9%86	2026-07-01 09:43:53.636443+00	t	22
412	1421771	توسعه‌دهنده اپلیکیشن موبایل	صنایع الکترونیک سایلکس	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1421771	2026-07-05 07:28:52.07242+00	t	21
338	1421701	توسعه‌دهنده ارشد بک‌اند و فرانت‌اند	مرکز تحقیقات مخابرات ایران	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1421701	2026-07-01 10:28:52.642417+00	t	21
426	1441684	Senior Front-End Developer	صراف	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1441684	2026-07-07 14:43:51.667715+00	t	21
427	1423655	Backend Developer (Node.js)	امن افزار	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1423655	2026-07-08 07:28:51.77154+00	t	21
441	tGaf	کارآموز برنامه‌نویسی Front-End (ReactJS-حوزه توسعه نرم افزار ERP)	رهجو ایجاد رویش آینده‌ساز | RIRA	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/rirais/jobs/tGaf/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%DA%A9%D8%A7%D8%B1%D8%A2%D9%85%D9%88%D8%B2-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3%DB%8C-front-end-reactjs-%D8%AD%D9%88%D8%B2%D9%87-%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D9%86%D8%B1%D9%85-%D8%A7%D9%81%D8%B2%D8%A7%D8%B1-erp-%D8%AF%D8%B1-%D8%B1%D9%87%D8%AC%D9%88-%D8%A7%DB%8C%D8%AC%D8%A7%D8%AF-%D8%B1%D9%88%DB%8C%D8%B4-%D8%A2%DB%8C%D9%86%D8%AF%D9%87-%D8%B3%D8%A7%D8%B2	2026-07-11 08:13:52.15699+00	t	22
462	tGNM	Product Designer	شنوتو | Shenoto	تهران، تهران	قرارداد پاره‌وقت	امروز	https://jobinja.ir/companies/shenoto/jobs/tGNM/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-product-designer-%D8%AF%D8%B1-%D8%B4%D9%86%D9%88%D8%AA%D9%88	2026-07-12 11:28:54.863985+00	t	27
456	tGSi	مدیر محصول (Product Manager)	شایان کیان نیوساد | Netrix	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/netrix/jobs/tGSi/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D9%85%D8%AF%DB%8C%D8%B1-%D9%85%D8%AD%D8%B5%D9%88%D9%84-product-manager-%D8%AF%D8%B1-%D8%B4%D8%A7%DB%8C%D8%A7%D9%86-%DA%A9%DB%8C%D8%A7%D9%86-%D9%86%DB%8C%D9%88%D8%B3%D8%A7%D8%AF	2026-07-12 11:28:54.841919+00	t	27
343	1382938	Full-Stack Developer	استودیو تاد	تهران، تهران	تمام وقت | دورکاری	2 روز پیش	https://jobvision.ir/jobs/1382938	2026-07-02 11:58:53.994202+00	t	24
344	1435351	برنامه نویس ارشد Flutter	چاوش داده پردازان فارس	فارس، شیراز	تمام وقت	3 روز پیش	https://jobvision.ir/jobs/1435351	2026-07-02 11:58:53.997787+00	t	24
345	1435341	برنامه‌نویس Flutter	شرکت داده نگار اقتصاد راهکار آینده یگانه یکتا	مازندران، بابلسر	تمام وقت	3 روز پیش	https://jobvision.ir/jobs/1435341	2026-07-02 11:58:54.000644+00	t	24
342	1437217	توسعه‌دهنده نرم‌افزار (Mid-Level)	خانه هوشمند کوباکو- اصفهان	اصفهان، اصفهان	تمام وقت	دیروز	https://jobvision.ir/jobs/1437217	2026-07-02 11:58:53.982993+00	t	24
355	1389918	برنامه نویس موبایل - Android	گروه فناوری اطلاعات ژنیک	گیلان، رشت	تمام وقت	32 روز پیش	https://jobvision.ir/jobs/1389918	2026-07-02 11:58:54.029527+00	t	24
356	1404557	Android Developer	تپسل	تهران، تهران	تمام وقت	33 روز پیش	https://jobvision.ir/jobs/1404557	2026-07-02 11:58:54.032174+00	t	24
357	1403342	کارآموز برنامه‌نویس موبایل (React Native یا Flutter)	هوشمند سازی نکسو	فارس، شیراز	تمام وقت | دورکاری | کارآموزی	36 روز پیش	https://jobvision.ir/jobs/1403342	2026-07-02 11:58:54.035224+00	t	24
358	1386501	برنامه نویس فرانت اند (Flutter)	سی گیت	تهران، تهران	تمام وقت	37 روز پیش	https://jobvision.ir/jobs/1386501	2026-07-02 11:58:54.039481+00	t	24
359	1392595	برنامه نویس اندروید	یکتا هوش ایرسا	اصفهان، اصفهان	تمام وقت	50 روز پیش	https://jobvision.ir/jobs/1392595	2026-07-02 11:58:54.04414+00	t	24
360	1387111	Electronics Circuit Design & Embedded Systems Engineer	امن افزار فناور ایفا	آذربایجان شرقی، تبریز	تمام وقت | دورکاری	56 روز پیش	https://jobvision.ir/jobs/1387111	2026-07-02 11:58:54.048032+00	t	24
361	1250363	برنامه نویس Flutter	پرداخت نوین آرین	تهران، تهران	تمام وقت	60 روز پیش	https://jobvision.ir/jobs/1250363	2026-07-02 11:58:54.053185+00	t	24
413	tGJz	Senior Front-End Developer (آقا-دورکاری)	داتوس تک | Datoos Tech	تهران، تهران	قرارداد دورکاری	امروز	https://jobinja.ir/companies/datoostech/jobs/tGJz/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-front-end-developer-%D8%A2%D9%82%D8%A7-%D8%AF%D9%88%D8%B1%DA%A9%D8%A7%D8%B1%DB%8C-%D8%AF%D8%B1-%D8%AF%D8%A7%D8%AA%D9%88%D8%B3-%D8%AA%DA%A9	2026-07-05 08:58:51.974684+00	t	22
428	tGbw	برنامه‌نویس Flutter (شیراز)	چادکو | Chadco	فارس، شیراز	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/chadco/jobs/tGbw/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-flutter-%D8%B4%DB%8C%D8%B1%D8%A7%D8%B2-%D8%AF%D8%B1-%DA%86%D8%A7%D8%AF%DA%A9%D9%88	2026-07-08 07:28:53.174591+00	t	25
442	1422434	ادمین اینستاگرام - خانم	آنی بار	تهران، تهران	پاره وقت	امروز	https://jobvision.ir/jobs/1422434	2026-07-11 08:58:53.166491+00	t	24
366	52329223	برنامه‌نویس جونیور لاراول 		رشت	تمام وقت		https://www.e-estekhdam.com/kmouqr-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%88%DB%8C%D8%B3-%D8%AC%D9%88%D9%86%DB%8C%D9%88%D8%B1-%D9%84%D8%A7%D8%B1%D8%A7%D9%88%D9%84-%D8%AF	2026-07-02 11:58:54.46174+00	t	23
362	52342518	برنامه نویس فلاتر	SPORT 724	مشهد، منطقه ۱۱، آزادشهر	تمام وقت		https://www.e-estekhdam.com/ka4hv5-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-%D9%81%D9%84%D8%A7%D8%AA%D8%B1-%D8%AF%D8%B1-sport-724-%D8%AF%D8%B1-%D9%85%D8%AD%D8%AF%D9%88	2026-07-02 11:58:54.446462+00	t	23
414	1350117	برنامه‌نویس فرانت‌اند (Front-End Developer)	ایکس چیف	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1350117	2026-07-05 13:58:51.772553+00	t	21
429	tguP	Senior Front-End Developer (React/Next.js)	اسنپ تریپ | Snapp Trip	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/pintapin/jobs/tguP/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-front-end-developer-react-next-js-%D8%AF%D8%B1-%D8%A7%D8%B3%D9%86%D9%BE-%D8%AA%D8%B1%DB%8C%D9%BE	2026-07-08 07:58:51.928678+00	t	22
363	52342517	استخدام ۸ عنوان شغلی	SPORT 724	مشهد، منطقه ۱۱، آزادشهر	تمام وقت | پاره وقت		https://www.e-estekhdam.com/kmlyhy-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%DB%B8-%D8%B9%D9%86%D9%88%D8%A7%D9%86-%D8%B4%D8%BA%D9%84%DB%8C-%D8%AF%D8%B1-sport-724-%D8%AF%D8%B1-%D9%85%D8%AD%D8%AF%D9%88%D8%AF%D9%87-%D8%A2%D8%B2	2026-07-02 11:58:54.451559+00	t	23
364	52347600	Flutter Developer	چادکو	شیراز، منطقه ۱، سینما سعدی	تمام وقت		https://www.e-estekhdam.com/k70jma-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-flutter-developer-%D8%AF%D8%B1-%DA%86%D8%A7%D8%AF%DA%A9%D9%88-%D8%AF%D8%B1-%D9%85%D8%AD%D8%AF%D9%88%D8%AF%D9%87-%D8%B3%DB%8C%D9%86%D9%85%D8%A7-%D8%B3	2026-07-02 11:58:54.455261+00	t	23
365	52324605	استخدام ۱۷ عنوان شغلی	آکادمی دکتر دارایی	بابلسر	تمام وقت		https://www.e-estekhdam.com/kjlkyo-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%DB%B1%DB%B7-%D8%B9%D9%86%D9%88%D8%A7%D9%86-%D8%B4%D8%BA%D9%84%DB%8C-%D8%AF%D8%B1-%D8%A2%DA%A9%D8%A7%D8%AF%D9%85%DB%8C-%D8%AF%DA%A9%D8%AA%D8%B1-%D8%AF	2026-07-02 11:58:54.458969+00	t	23
367	52319884	برنامه‌نویس اندروید	تجارت الکترونیک هامون	اصفهان، منطقه ۵، سیچان	تمام وقت		https://www.e-estekhdam.com/k9hady-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%88%DB%8C%D8%B3-%D8%A7%D9%86%D8%AF%D8%B1%D9%88%DB%8C%D8%AF-%D8%AF%D8%B1-%D8%AA%D8%AC%D8%A7%D8%B1	2026-07-02 11:58:54.464728+00	t	23
368	52307038	Flutter or React Native Developer		تهران	تمام وقت | پروژه‌ای		https://www.e-estekhdam.com/krnd0c-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-flutter-or-react-native-developer-%D8%AF%D8%B1-%D8%AA%D9%87%D8%B1%D8%A7%D9%86	2026-07-02 11:58:54.467121+00	t	23
369	52306570	برنامه نویس ASP.NET، هوش مصنوعی و اپلیکیشن موبایل	تحلیل گران آمارد نوین آمل	آمل	تمام وقت		https://www.e-estekhdam.com/kdxdjf-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-asp-net-%D9%87%D9%88%D8%B4-%D9%85%D8%B5%D9%86%D9%88%D8%B9%DB%8C-%D9%88-%D8%A7%D9%BE%D9%84	2026-07-02 11:58:54.469193+00	t	23
370	52298101	برنامه‌نویس جونیور لاراول 		رشت	تمام وقت		https://www.e-estekhdam.com/kj02ra-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%88%DB%8C%D8%B3-%D8%AC%D9%88%D9%86%DB%8C%D9%88%D8%B1-%D9%84%D8%A7%D8%B1%D8%A7%D9%88%D9%84-%D8%AF	2026-07-02 11:58:54.471675+00	t	23
371	52300588	Flutter Developer	چادکو	شیراز، منطقه ۱، سینما سعدی	تمام وقت		https://www.e-estekhdam.com/ko0n1r-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-flutter-developer-%D8%AF%D8%B1-%DA%86%D8%A7%D8%AF%DA%A9%D9%88-%D8%AF%D8%B1-%D9%85%D8%AD%D8%AF%D9%88%D8%AF%D9%87-%D8%B3%DB%8C%D9%86%D9%85%D8%A7-%D8%B3	2026-07-02 11:58:54.476075+00	t	23
372	52292040	متخصص برنامه نویس و شبکه	استودیو دیجیتال مارکتینگ M2	منطقه ۱، فرمانیه	تمام وقت		https://www.e-estekhdam.com/ko0jzl-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D9%85%D8%AA%D8%AE%D8%B5%D8%B5-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-%D9%88-%D8%B4%D8%A8%DA%A9%D9%87-%D8%AF%D8%B1-%D8%A7%D8%B3	2026-07-02 11:58:54.480735+00	t	23
373	52290702	برنامه نویس		منطقه ۱، زعفرانیه	تمام وقت		https://www.e-estekhdam.com/krisol-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-%D8%AF%D8%B1-%D9%85%D8%AD%D8%AF%D9%88%D8%AF%D9%87-%D8%B2%D8%B9%D9%81%D8%B1%D8%A7%D9%86	2026-07-02 11:58:54.485877+00	t	23
374	52282609	کارآموز فلاتر	شیوا افق فردا	منطقه ۶، توانیر	تمام وقت | کارآموزی		https://www.e-estekhdam.com/k1jc36-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%DA%A9%D8%A7%D8%B1%D8%A2%D9%85%D9%88%D8%B2-%D9%81%D9%84%D8%A7%D8%AA%D8%B1-%D8%AF%D8%B1-%D8%B4%DB%8C%D9%88%D8%A7-%D8%A7%D9%81%D9%82-%D9%81%D8%B1%D8%AF	2026-07-02 11:58:54.490212+00	t	23
375	52279602	برنامه‌نویس Flutter Dart	ایمن حصار پویا	تبریز	تمام وقت		https://www.e-estekhdam.com/kfk62y-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%88%DB%8C%D8%B3-flutter-dart-%D8%AF%D8%B1-%D8%A7%DB%8C%D9%85%D9%86-%D8%AD%D8%B5%D8%A7%D8%B1-%D9%BE	2026-07-02 11:58:54.494884+00	t	23
376	52275345	برنامه نویس Full Stack		شهرک صنعتی جی	تمام وقت		https://www.e-estekhdam.com/kp1wpr-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-full-stack-%D8%AF%D8%B1-%D8%B4%D9%87%D8%B1%DA%A9-%D8%B5%D9%86%D8%B9%D8%AA%DB%8C-%D8%AC	2026-07-02 11:58:54.501442+00	t	23
377	52269082	مدرس برنامه نویسی	مجتمع فنی تهران	اسلامشهر	پاره وقت		https://www.e-estekhdam.com/ketjxp-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D9%85%D8%AF%D8%B1%D8%B3-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3%DB%8C-%D8%AF%D8%B1-%D9%85%D8%AC%D8%AA%D9%85%D8%B9-%D9%81%D9%86	2026-07-02 11:58:54.506233+00	t	23
443	1444684	Senior Front-End Developer (React)	کیپا	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1444684	2026-07-11 09:28:52.774399+00	t	21
444	1444528	کارآموز برنامه‌نویسی Front-End (ReactJS)	ریرا	تهران، تهران	تمام وقت | دورکاری | کارآموزی	امروز	https://jobvision.ir/jobs/1444528	2026-07-11 09:28:52.780627+00	t	21
445	1444697	توسعه‌دهنده عامل هوش مصنوعی (AI Agent Developer)	شرکت داده و اعتبار سنجی تجارت ایرانیان (داتا)	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1444697	2026-07-11 09:28:52.783688+00	t	21
474	tGRw	Product Manager Assistant	وایب | Vibe	تهران، تهران	قرارداد تمام‌وقت	۲ روز پیش	https://jobinja.ir/companies/pazhouhande-rah/jobs/tGRw/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-product-manager-assistant-%D8%AF%D8%B1-%D9%88%D8%A7%DB%8C%D8%A8	2026-07-12 11:28:54.902135+00	t	27
378	52264963	برنامه نویس ASP.NET، هوش مصنوعی و اپلیکیشن موبایل	تحلیل گران آمارد نوین آمل	آمل	تمام وقت		https://www.e-estekhdam.com/kajl16-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-asp-net-%D9%87%D9%88%D8%B4-%D9%85%D8%B5%D9%86%D9%88%D8%B9%DB%8C-%D9%88-%D8%A7%D9%BE%D9%84	2026-07-02 11:58:54.509124+00	t	23
379	52264246	برنامه‌نویس فلاتر (Flutter Developer)	گروه تجارت اپتیک	منطقه ۶، دانشگاه تهران	تمام وقت | پاره وقت | پروژه‌ای		https://www.e-estekhdam.com/khuvfj-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%88%DB%8C%D8%B3-%D9%81%D9%84%D8%A7%D8%AA%D8%B1-flutter-developer-%D8%AF%D8%B1-%DA%AF%D8%B1%D9%88	2026-07-02 11:58:54.512837+00	t	23
380	52257285	Full-Stack Developer	عماریار	منطقه ۶، دانشگاه تهران	تمام وقت | پروژه‌ای		https://www.e-estekhdam.com/k7t3s9-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-full-stack-developer-%D8%AF%D8%B1-%D8%B9%D9%85%D8%A7%D8%B1%DB%8C%D8%A7%D8%B1-%D8%AF%D8%B1-%D9%85%D8%AD%D8%AF%D9%88%D8%AF%D9%87-%D8%AF%D8%A7%D9%86%D8%B4	2026-07-02 11:58:54.517512+00	t	23
381	52253462	برنامه نویس	فناوران آتیه ورزان هوشمند	منطقه ۳، آرارات	تمام وقت | دورکاری		https://www.e-estekhdam.com/kdet6j-%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-%D8%AF%D8%B1-%D9%81%D9%86%D8%A7%D9%88%D8%B1%D8%A7%D9%86-%D8%A2%D8%AA%DB%8C%D9%87-%D9%88	2026-07-02 11:58:54.522149+00	t	23
415	tGzG	Mid-level Front-End Developer	نیک زرپی | Zarpay	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/zarpay/jobs/tGzG/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-mid-level-front-end-developer-%D8%AF%D8%B1-%D9%86%DB%8C%DA%A9-%D8%B2%D8%B1%D9%BE%DB%8C	2026-07-05 14:13:52.048645+00	t	22
430	1442394	کارشناس ارشد طراحی و توسعه WordPress	گالری ایران زمین	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1442394	2026-07-08 09:28:51.641874+00	t	21
446	tGa8	(Senior Front-End Developer (React	کیپا | Keepa	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/Keepa/jobs/tGa8/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-front-end-developer-react-%D8%AF%D8%B1-%DA%A9%DB%8C%D9%BE%D8%A7	2026-07-11 10:13:52.190957+00	t	22
457	tGuS	طراح محصول ارشد	پویان ارتباط مدرن پارسه | Pump	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/pump-2/jobs/tGuS/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%B7%D8%B1%D8%A7%D8%AD-%D9%85%D8%AD%D8%B5%D9%88%D9%84-%D8%A7%D8%B1%D8%B4%D8%AF-%D8%AF%D8%B1-%D9%BE%D9%88%DB%8C%D8%A7%D9%86-%D8%A7%D8%B1%D8%AA%D8%A8%D8%A7%D8%B7-%D9%85%D8%AF%D8%B1%D9%86-%D9%BE%D8%A7%D8%B1%D8%B3%D9%87	2026-07-12 11:28:54.847235+00	t	27
458	tGZS	Chief Product technology officer (CPTO)	بیراد | Birad	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/Birad/jobs/tGZS/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-chief-product-technology-officer-cpto-%D8%AF%D8%B1-%D8%A8%DB%8C%D8%B1%D8%A7%D8%AF	2026-07-12 11:28:54.850792+00	t	27
459	tG26	Product Designer	پیشگامان زرین همراه | PZH	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/gerami-pzh/jobs/tG26/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-product-designer-%D8%AF%D8%B1-%D9%BE%DB%8C%D8%B4%DA%AF%D8%A7%D9%85%D8%A7%D9%86-%D8%B2%D8%B1%DB%8C%D9%86-%D9%87%D9%85%D8%B1%D8%A7%D9%87	2026-07-12 11:28:54.854389+00	t	27
460	tGEU	Associate Product Owner	کارگزاری مفید | Mofid Securities	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/mofid-securities/jobs/tGEU/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-associate-product-owner-%D8%AF%D8%B1-%DA%A9%D8%A7%D8%B1%DA%AF%D8%B2%D8%A7%D8%B1%DB%8C-%D9%85%D9%81%DB%8C%D8%AF	2026-07-12 11:28:54.857459+00	t	27
383	tZ5L	Senior Flutter Developer	گپیدو | Gapido	تهران، تهران	قرارداد تمام‌وقت	۳ روز پیش	https://jobinja.ir/companies/tahlilgaran-1/jobs/tZ5L/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-flutter-developer-%D8%AF%D8%B1-%DA%AF%D9%BE%DB%8C%D8%AF%D9%88	2026-07-02 11:58:54.749855+00	t	25
382	toF3	توسعه‌دهنده Flutter (کاشان-دورکاری)	هوش زیست دانژه | Hoosh Zist Danzheh	اصفهان، کاشان	قرارداد دورکاری	۱ روز پیش	https://jobinja.ir/companies/mugundmug/jobs/toF3/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D8%AF%D9%87%D9%86%D8%AF%D9%87-flutter-%DA%A9%D8%A7%D8%B4%D8%A7%D9%86-%D8%AF%D9%88%D8%B1%DA%A9%D8%A7%D8%B1%DB%8C-%D8%AF%D8%B1-%D9%87%D9%88%D8%B4-%D8%B2%DB%8C%D8%B3%D8%AA-%D8%AF%D8%A7%D9%86%DA%98%D9%87	2026-07-02 11:58:54.745624+00	t	25
461	tGEV	Senior Product Manager	پیشگامان زرین همراه | PZH	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/gerami-pzh/jobs/tGEV/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-product-manager-%D8%AF%D8%B1-%D9%BE%DB%8C%D8%B4%DA%AF%D8%A7%D9%85%D8%A7%D9%86-%D8%B2%D8%B1%DB%8C%D9%86-%D9%87%D9%85%D8%B1%D8%A7%D9%87	2026-07-12 11:28:54.860581+00	t	27
463	tGj8	مشاور فنی فروش و استقرار محصول (Field Product Consultant)	کیلید | Kilid	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/kilid-1/jobs/tGj8/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D9%85%D8%B4%D8%A7%D9%88%D8%B1-%D9%81%D9%86%DB%8C-%D9%81%D8%B1%D9%88%D8%B4-%D9%88-%D8%A7%D8%B3%D8%AA%D9%82%D8%B1%D8%A7%D8%B1-%D9%85%D8%AD%D8%B5%D9%88%D9%84-field-product-consultant-%D8%AF%D8%B1-%DA%A9%DB%8C%D9%84%DB%8C%D8%AF	2026-07-12 11:28:54.868281+00	t	27
464	tGjN	Product Designer	میزگرد نرم‌افزار | Round Table Apps	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/roundtableapps/jobs/tGjN/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-product-designer-%D8%AF%D8%B1-%D9%85%DB%8C%D8%B2%DA%AF%D8%B1%D8%AF-%D9%86%D8%B1%D9%85-%D8%A7%D9%81%D8%B2%D8%A7%D8%B1	2026-07-12 11:28:54.872132+00	t	27
416	1420081	برنامه نویس Full-Stack	پژوهشگاه نصر	تهران، تهران	تمام وقت یا پاره وقت	10 روز پیش	https://jobvision.ir/jobs/1420081	2026-07-06 07:28:51.618271+00	t	21
431	1438233	توسعه‌دهنده Flutter	همراه جیب	تهران، تهران	تمام وقت	امروز	https://jobvision.ir/jobs/1438233	2026-07-08 10:28:52.468837+00	t	24
447	tGGy	Senior Front-End Developer (React/Next.js)	هوشمند انرژی زی‌ما | Zima Smart Energy	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/zima-smart-energy/jobs/tGGy/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-front-end-developer-react-next-js-%D8%AF%D8%B1-%D9%87%D9%88%D8%B4%D9%85%D9%86%D8%AF-%D8%A7%D9%86%D8%B1%DA%98%DB%8C-%D8%B2%DB%8C-%D9%85%D8%A7	2026-07-11 10:43:52.28822+00	t	22
465	tGjP	مالک محصول (Product Owner)	رایان پرداز کاوش | Rayan Pardaz Kavosh	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/rayan-pardaz-kavosh/jobs/tGjP/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D9%85%D8%A7%D9%84%DA%A9-%D9%85%D8%AD%D8%B5%D9%88%D9%84-product-owner-%D8%AF%D8%B1-%D8%B1%D8%A7%DB%8C%D8%A7%D9%86-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2-%DA%A9%D8%A7%D9%88%D8%B4	2026-07-12 11:28:54.875513+00	t	27
384	taUx	برنامه‌نویسی موبایل (Flutter-اصفهان)	میزان گستر علم و دانش | Mizan Gostar Elm Va Danesh	اصفهان، اصفهان	قرارداد تمام‌وقت	۷ روز پیش	https://jobinja.ir/companies/mizangostar-elm-va-danesh/jobs/taUx/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3%DB%8C-%D9%85%D9%88%D8%A8%D8%A7%DB%8C%D9%84-flutter-%D8%A7%D8%B5%D9%81%D9%87%D8%A7%D9%86-%D8%AF%D8%B1-%D9%85%DB%8C%D8%B2%D8%A7%D9%86-%DA%AF%D8%B3%D8%AA%D8%B1-%D8%B9%D9%84%D9%85-%D9%88-%D8%AF%D8%A7%D9%86%D8%B4	2026-07-02 11:58:54.753103+00	t	25
385	taF2	کاراموز فلاتر	اچ ار باکس | HRBOX	تهران، تهران	قرارداد تمام‌وقت	۱۰ روز پیش	https://jobinja.ir/companies/hrbox/jobs/taF2/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%DA%A9%D8%A7%D8%B1%D8%A7%D9%85%D9%88%D8%B2-%D9%81%D9%84%D8%A7%D8%AA%D8%B1-%D8%AF%D8%B1-%D8%A7%DA%86-%D8%A7%D8%B1-%D8%A8%D8%A7%DA%A9%D8%B3	2026-07-02 11:58:54.75629+00	t	25
386	taIy	Flutter Developer	نقش اول کیفیت | Naghsh Aval Keyfiat	تهران، تهران	قرارداد تمام‌وقت	۱۰ روز پیش	https://jobinja.ir/companies/naghsh-aval-keyfiat/jobs/taIy/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-flutter-developer-%D8%AF%D8%B1-%D9%86%D9%82%D8%B4-%D8%A7%D9%88%D9%84-%DA%A9%DB%8C%D9%81%DB%8C%D8%AA	2026-07-02 11:58:54.759544+00	t	25
387	to7d	Flutter Developer (ساری)	درنیکا | DORNICA	مازندران، ساری	قرارداد تمام‌وقت	۱۱ روز پیش	https://jobinja.ir/companies/dornica-4/jobs/to7d/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-flutter-developer-%D8%B3%D8%A7%D8%B1%DB%8C-%D8%AF%D8%B1-%D8%AF%D8%B1%D9%86%DB%8C%DA%A9%D8%A7	2026-07-02 11:58:54.762764+00	t	25
388	tpiT	برنامه‌نویس Flutter (دورکاری-مشهد)	ژرف‌اندیشان | Xplormind	خراسان رضوی، مشهد	قرارداد دورکاری	۱۳ روز پیش	https://jobinja.ir/companies/xplormind/jobs/tpiT/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-flutter-%D8%AF%D9%88%D8%B1%DA%A9%D8%A7%D8%B1%DB%8C-%D9%85%D8%B4%D9%87%D8%AF-%D8%AF%D8%B1-%DA%98%D8%B1%D9%81-%D8%A7%D9%86%D8%AF%DB%8C%D8%B4%D8%A7%D9%86	2026-07-02 11:58:54.767844+00	t	25
389	taCV	برنامه‌نویس فلاتر (Flutter-شیراز)	تاو سیستم | Taav System	فارس، شیراز	قرارداد تمام‌وقت	۱۴ روز پیش	https://jobinja.ir/companies/taav-system/jobs/taCV/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-%D9%81%D9%84%D8%A7%D8%AA%D8%B1-flutter-%D8%B4%DB%8C%D8%B1%D8%A7%D8%B2-%D8%AF%D8%B1-%D8%AA%D8%A7%D9%88-%D8%B3%DB%8C%D8%B3%D8%AA%D9%85	2026-07-02 11:58:54.771264+00	t	25
390	tpHI	برنامه‌نویس Flutter (آقا)	داده پروران مهدا | Dadeh Parvaran Mahda	تهران، تهران	قرارداد تمام‌وقت	۱۴ روز پیش	https://jobinja.ir/companies/dadeh-parvaran-mahda/jobs/tpHI/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-flutter-%D8%A2%D9%82%D8%A7-%D8%AF%D8%B1-%D8%AF%D8%A7%D8%AF%D9%87-%D9%BE%D8%B1%D9%88%D8%B1%D8%A7%D9%86-%D9%85%D9%87%D8%AF%D8%A7	2026-07-02 11:58:54.77573+00	t	25
391	taYX	Mobile App Developer	آلومینیوم دیتاست | Aluminium Dataset	تهران، تهران	قرارداد تمام‌وقت	۱۴ روز پیش	https://jobinja.ir/companies/aluminium-dataset/jobs/taYX/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-mobile-app-developer-%D8%AF%D8%B1-%D8%A2%D9%84%D9%88%D9%85%DB%8C%D9%86%DB%8C%D9%88%D9%85-%D8%AF%DB%8C%D8%AA%D8%A7%D8%B3%D8%AA	2026-07-02 11:58:54.780115+00	t	25
394	tpQv	برنامه‌نویس فول استک (Full-Stack-PHP)	شیووچی | Shivochi	تهران، تهران	قرارداد تمام‌وقت	۱۶ روز پیش	https://jobinja.ir/companies/shivochi/jobs/tpQv/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-%D9%81%D9%88%D9%84-%D8%A7%D8%B3%D8%AA%DA%A9-full-stack-php-%D8%AF%D8%B1-%D8%B4%DB%8C%D9%88%D9%88%DA%86%DB%8C	2026-07-02 11:58:54.797026+00	t	25
466	tGjM	Product Sales Specialist (Gold)	دیجی‌‌کالا | Digikala	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/digikala/jobs/tGjM/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-product-sales-specialist-gold-%D8%AF%D8%B1-%D8%AF%DB%8C%D8%AC%DB%8C-%DA%A9%D8%A7%D9%84%D8%A7	2026-07-12 11:28:54.878644+00	t	27
467	tG74	Senior product security expert	صراف | Saraf	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/saraf-4/jobs/tG74/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-product-security-expert-%D8%AF%D8%B1-%D8%B5%D8%B1%D8%A7%D9%81	2026-07-12 11:28:54.88147+00	t	27
468	tG76	Product Manager	دیجی‌‌کالا | Digikala	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/digikala/jobs/tG76/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-product-manager-%D8%AF%D8%B1-%D8%AF%DB%8C%D8%AC%DB%8C-%DA%A9%D8%A7%D9%84%D8%A7	2026-07-12 11:28:54.884367+00	t	27
392	tpsL	برنامه‌نویس Flutter (بابلسر)	داده‌نگار اقتصاد | DadeNegar Eghtesad	مازندران، بابلسر	قرارداد پاره‌وقت	۱۵ روز پیش	https://jobinja.ir/companies/daraei-holding/jobs/tpsL/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-flutter-%D8%A8%D8%A7%D8%A8%D9%84%D8%B3%D8%B1-%D8%AF%D8%B1-%D8%AF%D8%A7%D8%AF%D9%87-%D9%86%DA%AF%D8%A7%D8%B1-%D8%A7%D9%82%D8%AA%D8%B5%D8%A7%D8%AF	2026-07-02 11:58:54.785039+00	t	25
393	tpQj	برنامه‌نویس Full Stack (.NET & Flutter)	شیووچی | Shivochi	تهران، تهران	قرارداد تمام‌وقت	۱۶ روز پیش	https://jobinja.ir/companies/shivochi/jobs/tpQj/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-full-stack-net-flutter-%D8%AF%D8%B1-%D8%B4%DB%8C%D9%88%D9%88%DA%86%DB%8C	2026-07-02 11:58:54.792006+00	t	25
395	tp0v	برنامه‌نویس Flutter	وینرک | ٰVinerck	تهران، تهران	قرارداد تمام‌وقت	۱۶ روز پیش	https://jobinja.ir/companies/vinerck-1/jobs/tp0v/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-flutter-%D8%AF%D8%B1-%D9%88%DB%8C%D9%86%D8%B1%DA%A9	2026-07-02 11:58:54.800622+00	t	25
396	tprk	کار آموز توسعه دهنده فلاتر(اپلیکیشن موبایل)	پویا تدبیر کارآمد | Pooya Tadbir Karamad	تهران، تهران	قرارداد تمام‌وقت	۱۹ روز پیش	https://jobinja.ir/companies/pooya-tadbir-karamad/jobs/tprk/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%DA%A9%D8%A7%D8%B1-%D8%A2%D9%85%D9%88%D8%B2-%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D8%AF%D9%87%D9%86%D8%AF%D9%87-%D9%81%D9%84%D8%A7%D8%AA%D8%B1-%D8%A7%D9%BE%D9%84%DB%8C%DA%A9%DB%8C%D8%B4%D9%86-%D9%85%D9%88%D8%A8%D8%A7%DB%8C%D9%84-%D8%AF%D8%B1-%D9%BE%D9%88%DB%8C%D8%A7-%D8%AA%D8%AF%D8%A8%DB%8C%D8%B1-%DA%A9%D8%A7%D8%B1%D8%A2%D9%85%D8%AF	2026-07-02 11:58:54.804047+00	t	25
397	tpgG	برنامه‌نویس Flutter	ایکس پی | Xpay	تهران، تهران	قرارداد تمام‌وقت	۲۲ روز پیش	https://jobinja.ir/companies/Xpay/jobs/tpgG/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-flutter-%D8%AF%D8%B1-%D8%A7%DB%8C%DA%A9%D8%B3-%D9%BE%DB%8C	2026-07-02 11:58:54.808301+00	t	25
398	RQqb	برنامه‌نویس Flutter	سروشان | Sorooshan	تهران، تهران	قرارداد تمام‌وقت	۲۳ روز پیش	https://jobinja.ir/companies/sorooshan-1/jobs/RQqb/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-flutter-%D8%AF%D8%B1-%D8%B3%D8%B1%D9%88%D8%B4%D8%A7%D9%86	2026-07-02 11:58:54.812311+00	t	25
399	tpAE	Mid‑Level) Flutter Developer)	کنسی | CanC	تهران، تهران	قرارداد تمام‌وقت	۲۵ روز پیش	https://jobinja.ir/companies/canc/jobs/tpAE/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-mid-level-flutter-developer-%D8%AF%D8%B1-%DA%A9%D9%86%D8%B3%DB%8C	2026-07-02 11:58:54.815815+00	t	25
400	tpAM	Senior Flutter Developer	کنسی | CanC	تهران، تهران	قرارداد تمام‌وقت	۲۵ روز پیش	https://jobinja.ir/companies/canc/jobs/tpAM/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-senior-flutter-developer-%D8%AF%D8%B1-%DA%A9%D9%86%D8%B3%DB%8C	2026-07-02 11:58:54.819776+00	t	25
401	tpYC	توسعه‌دهنده Flutter (شیراز)	پویا رایانه دنا | PRDCo	فارس، شیراز	قرارداد تمام‌وقت	۲۶ روز پیش	https://jobinja.ir/companies/prdco/jobs/tpYC/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D8%AF%D9%87%D9%86%D8%AF%D9%87-flutter-%D8%B4%DB%8C%D8%B1%D8%A7%D8%B2-%D8%AF%D8%B1-%D9%BE%D9%88%DB%8C%D8%A7-%D8%B1%D8%A7%DB%8C%D8%A7%D9%86%D9%87-%D8%AF%D9%86%D8%A7	2026-07-02 11:58:54.824268+00	t	25
417	1423382	Full Stack Developer (PHP, Laravel, ReactJS, MySQL)	مرکز حمل بار بارسان 4818	تهران، تهران	تمام وقت	10 روز پیش	https://jobvision.ir/jobs/1423382	2026-07-06 11:13:51.808992+00	t	21
432	tZHA	توسعه‌دهنده‌ React	گروه حصین | Hasin Technology	تهران، تهران	قرارداد تمام‌وقت	امروز	https://jobinja.ir/companies/hasin/jobs/tZHA/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D8%AF%D9%87%D9%86%D8%AF%D9%87-react-%D8%AF%D8%B1-%DA%AF%D8%B1%D9%88%D9%87-%D8%AD%D8%B5%DB%8C%D9%86	2026-07-08 12:28:52.041347+00	t	22
448	1412710	کارشناس ارشد تست نرم افزار (QA)	سکوی تبادل فردا	تهران، تهران	تمام وقت	35 روز پیش	https://jobvision.ir/jobs/1412710	2026-07-11 13:43:52.112154+00	t	21
469	tG4q	مالک محصول (Product Owner)	فلای تودی | Flytoday	تهران، تهران	قرارداد تمام‌وقت	۱ روز پیش	https://jobinja.ir/companies/abnoos-gasht-tehran/jobs/tG4q/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D9%85%D8%A7%D9%84%DA%A9-%D9%85%D8%AD%D8%B5%D9%88%D9%84-product-owner-%D8%AF%D8%B1-%D9%81%D9%84%D8%A7%DB%8C-%D8%AA%D9%88%D8%AF%DB%8C	2026-07-12 11:28:54.887536+00	t	27
470	tGGq	کارشناس محصول نرم افزار	دانا پرداز | DANA PARDAZ	تهران، تهران	قرارداد تمام‌وقت	۱ روز پیش	https://jobinja.ir/companies/danapardaz/jobs/tGGq/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%DA%A9%D8%A7%D8%B1%D8%B4%D9%86%D8%A7%D8%B3-%D9%85%D8%AD%D8%B5%D9%88%D9%84-%D9%86%D8%B1%D9%85-%D8%A7%D9%81%D8%B2%D8%A7%D8%B1-%D8%AF%D8%B1-%D8%AF%D8%A7%D9%86%D8%A7-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2	2026-07-12 11:28:54.890734+00	t	27
471	tk3G	سرپرست محصول	آسیاتک | Asiatech	تهران، تهران	قرارداد تمام‌وقت	۱ روز پیش	https://jobinja.ir/companies/asiatech/jobs/tk3G/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%B3%D8%B1%D9%BE%D8%B1%D8%B3%D8%AA-%D9%85%D8%AD%D8%B5%D9%88%D9%84-%D8%AF%D8%B1-%D8%A2%D8%B3%DB%8C%D8%A7%D8%AA%DA%A9	2026-07-12 11:28:54.893427+00	t	27
472	tGgi	دستیار مدیر محصول (APM)	هلدینگ چابک | Chabok Holding	تهران، تهران	قرارداد تمام‌وقت	۱ روز پیش	https://jobinja.ir/companies/matin/jobs/tGgi/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%AF%D8%B3%D8%AA%DB%8C%D8%A7%D8%B1-%D9%85%D8%AF%DB%8C%D8%B1-%D9%85%D8%AD%D8%B5%D9%88%D9%84-apm-%D8%AF%D8%B1-%D9%87%D9%84%D8%AF%DB%8C%D9%86%DA%AF-%DA%86%D8%A7%D8%A8%DA%A9	2026-07-12 11:28:54.896482+00	t	27
\.


--
-- Data for Name: jobs_searchquery; Type: TABLE DATA; Schema: public; Owner: jobbot
--

COPY public.jobs_searchquery (id, title, url, is_active, created_at, user_id) FROM stdin;
21	جاب‌ویژن: react (تهران)	https://jobvision.ir/jobs/keyword/react/category/in-all-cities-of-tehran/type/full-time?page=1&sort=0	t	2026-06-27 21:16:37.424532+00	4
22	جابینجا: react (تهران)	https://jobinja.ir/jobs?filters%5Bkeywords%5D%5B0%5D=react&filters%5Blocations%5D%5B%5D=%D8%AA%D9%87%D8%B1%D8%A7%D9%86&filters%5Bjob_types%5D%5B0%5D=is_fulltime&sort_by=published_at_desc	t	2026-06-27 21:16:37.426861+00	4
23	ای‌استخدام: flutter	https://www.e-estekhdam.com/search/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B5%D9%88%D8%B1%D8%AA-%D8%AA%D9%85%D8%A7%D9%85-%D9%88%D9%82%D8%AA--%D9%BE%D8%A7%D8%B1%D9%87-%D9%88%D9%82%D8%AA-%D8%A8%D8%B1%D8%A7%DB%8C-flutter?sort=%D8%AC%D8%AF%DB%8C%D8%AF%D8%AA%D8%B1%DB%8C%D9%86	t	2026-07-02 11:49:31.512123+00	1
24	جاب‌ویژن: flutter	https://jobvision.ir/jobs/keyword/flutter/type/full-time-and-part-time?page=1&sort=0	t	2026-07-02 11:49:31.51799+00	1
25	جابینجا: flutter	https://jobinja.ir/jobs?filters%5Bkeywords%5D%5B0%5D=flutter&filters%5Bjob_types%5D%5B0%5D=is_fulltime&filters%5Bjob_types%5D%5B1%5D=is_parttime&sort_by=published_at_desc	t	2026-07-02 11:49:31.519814+00	1
26	ایران‌تلنت: flutter	https://www.irantalent.com/jobs/jobs-in-Full-Time-employment-type-level-in-Part-Time-employment-type-level?keyword=flutter	t	2026-07-02 11:49:31.521858+00	1
27	جابینجا: Product designr (تهران)	https://jobinja.ir/jobs?filters%5Bkeywords%5D%5B0%5D=Product+designr&filters%5Blocations%5D%5B%5D=%D8%AA%D9%87%D8%B1%D8%A7%D9%86&filters%5Bjob_types%5D%5B0%5D=is_fulltime&filters%5Bjob_types%5D%5B1%5D=is_parttime&filters%5Bremote%5D=1&sort_by=published_at_desc	t	2026-07-12 11:22:23.635997+00	7
28	جاب‌ویژن: Product designr (تهران)	https://jobvision.ir/jobs/keyword/Product%20designr/category/in-all-cities-of-tehran/type/remote-and-full-time-and-part-time?page=1&sort=0	t	2026-07-12 11:22:23.641212+00	7
29	ای‌استخدام: Product designr (تهران)	https://www.e-estekhdam.com/search/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%AF%D8%B1-%D8%AA%D9%87%D8%B1%D8%A7%D9%86-%D8%A8%D8%B5%D9%88%D8%B1%D8%AA-%D8%AA%D9%85%D8%A7%D9%85-%D9%88%D9%82%D8%AA--%D9%BE%D8%A7%D8%B1%D9%87-%D9%88%D9%82%D8%AA--%D8%AF%D9%88%D8%B1%DA%A9%D8%A7%D8%B1%DB%8C-%D8%A8%D8%B1%D8%A7%DB%8C-Product%20designr?sort=%D8%AC%D8%AF%DB%8C%D8%AF%D8%AA%D8%B1%DB%8C%D9%86	t	2026-07-12 11:22:23.643124+00	7
30	ایران‌تلنت: Product designr (تهران)	https://www.irantalent.com/jobs/jobs-in-tehran-in-Full-Time-employment-type-level-in-Part-Time-employment-type-level-work-type-remote?keyword=Product%20designr	t	2026-07-12 11:22:23.644245+00	7
\.


--
-- Name: accounts_telegramuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jobbot
--

SELECT pg_catalog.setval('public.accounts_telegramuser_id_seq', 7, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jobbot
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jobbot
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jobbot
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 66, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jobbot
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jobbot
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jobbot
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jobbot
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jobbot
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 33, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jobbot
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 34, true);


--
-- Name: jobs_jobposting_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jobbot
--

SELECT pg_catalog.setval('public.jobs_jobposting_id_seq', 477, true);


--
-- Name: jobs_searchquery_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jobbot
--

SELECT pg_catalog.setval('public.jobs_searchquery_id_seq', 30, true);


--
-- Name: accounts_telegramuser accounts_telegramuser_chat_id_key; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.accounts_telegramuser
    ADD CONSTRAINT accounts_telegramuser_chat_id_key UNIQUE (chat_id);


--
-- Name: accounts_telegramuser accounts_telegramuser_pkey; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.accounts_telegramuser
    ADD CONSTRAINT accounts_telegramuser_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: jobs_jobposting jobs_jobposting_pkey; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.jobs_jobposting
    ADD CONSTRAINT jobs_jobposting_pkey PRIMARY KEY (id);


--
-- Name: jobs_searchquery jobs_searchquery_pkey; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.jobs_searchquery
    ADD CONSTRAINT jobs_searchquery_pkey PRIMARY KEY (id);


--
-- Name: jobs_jobposting uniq_job_per_search; Type: CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.jobs_jobposting
    ADD CONSTRAINT uniq_job_per_search UNIQUE (search_query_id, external_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: jobs_jobposting_search_query_id_390bd044; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX jobs_jobposting_search_query_id_390bd044 ON public.jobs_jobposting USING btree (search_query_id);


--
-- Name: jobs_searchquery_user_id_5bbf31fd; Type: INDEX; Schema: public; Owner: jobbot
--

CREATE INDEX jobs_searchquery_user_id_5bbf31fd ON public.jobs_searchquery USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jobs_jobposting jobs_jobposting_search_query_id_390bd044_fk_jobs_searchquery_id; Type: FK CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.jobs_jobposting
    ADD CONSTRAINT jobs_jobposting_search_query_id_390bd044_fk_jobs_searchquery_id FOREIGN KEY (search_query_id) REFERENCES public.jobs_searchquery(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jobs_searchquery jobs_searchquery_user_id_5bbf31fd_fk_accounts_telegramuser_id; Type: FK CONSTRAINT; Schema: public; Owner: jobbot
--

ALTER TABLE ONLY public.jobs_searchquery
    ADD CONSTRAINT jobs_searchquery_user_id_5bbf31fd_fk_accounts_telegramuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_telegramuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict tnmDS3axgSEXQGoJKrofj7GWQm8tPQg4CBYT1jqhUEi543fjSOIpv6KGTemV8dw

